name: Cypress Parallel Tests New

on: 
  workflow_dispatch:
    inputs:
      # environment:
      #   description: 'Environment to run tests against'    
      #   required: true
      #   type: string
      #   default: 'staging'

      # script:
      #   description: 'Script to run from package.json'
      #   required: true
      #   type: string
      #   default: 'triggerAllTests-headless' 

jobs:

  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
        browser: chrome
        headless: true
        record: true
        parallel: true
        # config-file: ${{ inputs.environment }}.json
        # working-directory: cypress/config/
        # command: npm run ${{ inputs.script }}
      env:
          # pass the Cypress Cloud record key as an environment variable
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # pass the project ID from the secrets through environment variable
        # CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}

    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: screenshots
        path: cypress/screenshots

    - name: Upload videos
      uses: actions/upload-artifact@v3
      if: always()  
      with:
        name: videos
        path: cypress/videos