name: Cypress Tests

on: [push]

jobs:

  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        headless: true
        config-file: $CONFIG_FILE 
        spec: ${{ matrix.containers == 1 && 'cypress/e2e/webdriver-uni/*' || matrix.containers == 2 && 'cypress/e2e/automation-test-store/*' || matrix.containers == 3 && 'cypress/e2e/test/*' || 'cypress/e2e/*' }}

    - name: Upload screenshots
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: screenshots
        path: cypress/screenshots

    - name: Upload videos
      uses: actions/upload-artifact@v2
      if: always()  
      with:
        name: videos
        path: cypress/videos